# Generated by Django 3.0.6 on 2020-06-11 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_page', models.IntegerField()),
                ('how_it_work_page', models.IntegerField()),
                ('home_page', models.IntegerField()),
                ('thank_you', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='competitors_info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('entries', models.IntegerField()),
                ('not_used_entries', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=0)),
                ('are_you_eating_heathier', models.BooleanField(default=0)),
                ('agree', models.BooleanField(default=0)),
                ('competition_given', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='initial_form_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('agree', models.BooleanField(default=0)),
                ('cookware_set', models.CharField(max_length=100)),
                ('other_cook_set', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='timer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='my_acc_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='')),
                ('bio', models.CharField(blank=True, max_length=1000, null=True)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='competitors_payment_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_id', models.CharField(max_length=200)),
                ('payer_mail', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('c_time', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=100)),
                ('payer_country_code', models.CharField(max_length=200)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitaral_nutrition_app.competitors_info')),
            ],
        ),
        migrations.CreateModel(
            name='competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(max_length=100)),
                ('i_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitaral_nutrition_app.competitors_info')),
            ],
        ),
    ]
