# Generated by Django 3.0.6 on 2020-06-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitaral_nutrition_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
