# Generated by Django 3.0.6 on 2020-06-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitaral_nutrition_app', '0003_auto_20200630_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer_info',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
